# -*- coding: utf-8 -*-
"""X\Twiter_Scraping_#ormas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpRKKUzMqbGT0kSE2nTtXeqSp2jCTc3t
"""

from google.colab import drive
drive.mount('/content/drive')

#Twitter Auth Token
twitter_auth_token = 'bb16faab35816a902f1c51eafb3bc86b32e9ca28' # change this auth token

# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

# Crawl Data

filename = '#organisasi masyarakat'
search_keyword = 'organisasi masyarakat since:2025-10-3 until:2025-10-30 lang:id'
limit = 37

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df.head(10))

import pandas as pd

# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")